#!/usr/bin/env node
// vim: set ft=javascript:
"use strict";

var fs          = require('fs'),
    common      = require('./common'),
    version     = require('./package.json').version,
    cli         = require('./cli');

function error(msg, showHelp) {
  if (showHelp)
    cli.showHelp();
  console.warn('error: ', msg);
  process.exit(1);
}

function pipe(a, b) {
  a.on('error', function(err) {
    error(err);
  });
  a.pipe(b);
}

var argv = cli.argv;

if (argv.help)
  return cli.showHelp();

if (argv.version)
  return console.log(version);

if (argv._.length === 0)
  error('provide bundle entry module as an argument', true);

if (argv.watch && !argv.output)
  error('provide output via -o/--output option', true);

var transform = [].concat(argv.t).concat(argv.transform);
var cssTransform = argv['css-transform'];
var globalTransform = argv['global-transform'];

var Composer = require('./index');

var composer = new Composer(argv._, {
  transform: transform,
  cssTransform: cssTransform,
  globalTransform: globalTransform,
  extensions: [].concat(argv.extension).filter(Boolean),
  debug: argv.debug,
  watch: argv.watch
});

var output = argv.output || argv.o;

function bundle() {
  var out = output ? fs.createWriteStream(output) : process.stdout;
  if (argv.js)
    pipe(composer.bundleJS(), out)
  else if (argv.css)
    pipe(composer.bundleCSS(), out)
  else
    pipe(composer.bundle(), out);
}

if (argv.watch) {
  console.log('starting to watch for source changes');
  composer.on('update', function() {
    console.log('source change detected, rebuilding bundle');
    bundle();
  });
}

bundle();
